name: Node.js Package, Github CI/CD Pipeline

on:
  push:
    branches: [main]
    paths-ignore:
      - ".github"
  pull_request:
    branches: [main]
    paths-ignore:
      - ".github"

jobs:
  release:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: https://registry.npmjs.org

      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
